name: API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies (root)
        run: npm install
      - name: Install backend dependencies
        run: npm install --prefix app/backend
      - name: Install API test dependencies
        run: npm install --prefix tests/api
      - name: Run API Tests
        run: npm test
        working-directory: tests/api
        env:
          PORT: 5000 # Ensure backend runs on this port for tests
          MONGO_URI: mongodb://localhost:27017/qa_challenge_test # Use a test database
          JWT_SECRET: supersecretjwtkey
